const attendanceData = [
  {
    id: 1,
    name: 'John Doe',
    department: 'Logistics',
    shift: '09:00 - 18:00',
    checkIn: '09:12',
    checkOut: '18:05',
    late: 12,
    status: 'Late',
    statusColor: 'yellow',
  },
  {
    id: 2,
    name: 'Alice Smith',
    department: 'Marketing',
    shift: '09:00 - 18:00',
    checkIn: '08:55',
    checkOut: '18:10',
    late: null,
    status: 'Present',
    statusColor: 'green',
  },
  {
    id: 3,
    name: 'Robert Johnson',
    department: 'Sales',
    shift: '10:00 - 19:00',
    checkIn: '09:58',
    checkOut: '19:02',
    late: null,
    status: 'Present',
    statusColor: 'green',
  },
  {
    id: 4,
    name: 'Emily Davis',
    department: 'HR',
    shift: '09:00 - 18:00',
    checkIn: '-',
    checkOut: '-',
    late: null,
    status: 'Absent',
    statusColor: 'red',
  },
  {
    id: 5,
    name: 'Michael Brown',
    department: 'Logistics',
    shift: '07:00 - 16:00',
    checkIn: '06:50',
    checkOut: '16:15',
    late: null,
    status: 'Present',
    statusColor: 'green',
  },
  {
    id: 6,
    name: 'Jessica Wilson',
    department: 'Marketing',
    shift: '09:00 - 18:00',
    checkIn: '09:02',
    checkOut: '18:01',
    late: 2,
    status: 'Present',
    statusColor: 'green',
  },
  {
    id: 7,
    name: 'David Martinez',
    department: 'Sales',
    shift: '10:00 - 19:00',
    checkIn: '10:45',
    checkOut: '19:30',
    late: 45,
    status: 'Late (Severe)',
    statusColor: 'red',
  },
  {
    id: 8,
    name: 'Sarah Connor',
    department: 'Sales',
    shift: '09:00 - 18:00',
    checkIn: '09:45',
    checkOut: '18:15',
    late: 45,
    status: 'Late',
    statusColor: 'yellow',
  },
]

export default attendanceData;